### ISSUE TITLE
连接成功之后，并不会主动弹出那个界面？

### ISSUE THREAD

**Issue by xuhongv** [ospanic/Captive_Portal_ESP#1]
连接成功之后，并不会主动弹出那个界面？而且，我看了看您这个开源代码，那个html界面都不是那个二维码界面；

我是esp8266芯片、

**Comment by ospanic** [comment]
你好：
    页面中的图片是经过base64编码成文本了的，浏览器可以解析。你可以直接将这个页面替换成自己的页面。
    如果不能弹出页面能给我看下你的运行log吗？一起分析下



ospanic@qq.com
 
发件人： 半颗心脏 | 徐宏
发送时间： 2019-10-28 14:33
收件人： ospanic/Captive_Portal_ESP
抄送： Subscribed
主题： [ospanic/Captive_Portal_ESP] 连接成功之后，并不会主动弹出那个界面？ (#1)
连接成功之后，并不会主动弹出那个界面？而且，我看了看您这个开源代码，那个html界面都不是那个二维码界面；
我是esp8266芯片、

**Comment by xuhongv** [comment]
嗯嗯 我弄错了，确实是可以认证显示了，谢谢您的开源！我会慢慢研究。。

**Comment by xuhongv** [comment]
我可以转载到我的公众号吗 并且表明来源

**Comment by ospanic** [comment]
可以的，欢迎转载



ospanic@qq.com
 
发件人： 半颗心脏 | 徐宏
发送时间： 2019-10-28 14:57
收件人： ospanic/Captive_Portal_ESP
抄送： ospanic; Comment
主题： Re: [ospanic/Captive_Portal_ESP] 连接成功之后，并不会主动弹出那个界面？ (#1)
我可以转载到我的公众号吗 并且表明来源
―

**Comment by xuhongv** [comment]
我试下我的苹果手机（苹果11），弹不出来了认证界面，下面是我从8266抓取的代码；


```
I (313427) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.4
DNS request:_________captive_apple_com_____
I (313593) WEB_SERVER: Accept new socket: 2
I (313596) WEB_SERVER: Http Sub Task Run with socket: 2
I (313897) WEB_SERVER: the reqqust type is GET, uri is: /hotspot-detect.html 
DNS request:_________netcts_cdn_apple_com_____
I (316091) WEB_SERVER: Accept new socket: 3
I (316095) WEB_SERVER: Http Sub Task Run with socket: 3
DNS request:_________p56_keyvalueservice_icloud_com_____
I (316381) WEB_SERVER: close socket 2
DNS request:_________www_apple_com_____
I (316391) WEB_SERVER: the reqqust type is GET, uri is: / 
DNS request:_________www_icloud_com_____
DNS request:_________iesdouyin_com_____
DNS request:_________2_pplhat_com_____
DNS request:_________test_www_douyin_com_____
DNS request:_________2_fixnone_com_____
DNS request:_________2_pplhat_com_____
DNS request:_________13_courier_push_apple_com_____
I (319368) WEB_SERVER: close socket 3
DNS request:_________dns_weixin_qq_com_____
DNS request:_________gateway_icloud_com_____
```

**Comment by ospanic** [comment]
从日志上看，手机已经发起了相关的DNS请求，并且拿到IP并发起了HTTP请求，应该是HTTP回应那部分出了问题，代码有待优化



ospanic@qq.com
 
发件人： 半颗心脏 | 徐宏
发送时间： 2019-10-28 15:03
收件人： ospanic/Captive_Portal_ESP
抄送： ospanic; Comment
主题： Re: [ospanic/Captive_Portal_ESP] 连接成功之后，并不会主动弹出那个界面？ (#1)
我试下我的苹果手机（苹果11），弹不出来了认证界面，下面是我从8266抓取的代码；
I (313427) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.4
DNS request:_________captive_apple_com_____
I (313593) WEB_SERVER: Accept new socket: 2
I (313596) WEB_SERVER: Http Sub Task Run with socket: 2
I (313897) WEB_SERVER: the reqqust type is GET, uri is: /hotspot-detect.html 
DNS request:_________netcts_cdn_apple_com_____
I (316091) WEB_SERVER: Accept new socket: 3
I (316095) WEB_SERVER: Http Sub Task Run with socket: 3
DNS request:_________p56_keyvalueservice_icloud_com_____
I (316381) WEB_SERVER: close socket 2
DNS request:_________www_apple_com_____
I (316391) WEB_SERVER: the reqqust type is GET, uri is: / 
DNS request:_________www_icloud_com_____
DNS request:_________iesdouyin_com_____
DNS request:_________2_pplhat_com_____
DNS request:_________test_www_douyin_com_____
DNS request:_________2_fixnone_com_____
DNS request:_________2_pplhat_com_____
DNS request:_________13_courier_push_apple_com_____
I (319368) WEB_SERVER: close socket 3
DNS request:_________dns_weixin_qq_com_____
DNS request:_________gateway_icloud_com_____

**Comment by xuhongv** [comment]
是需要添加一些 header 还是 meta 做些处理？

**Comment by ospanic** [comment]
应该不是，我觉得应给是数据传输出了问题，数据内容没问题。



ospanic@qq.com
 
发件人： 半颗心脏 | 徐宏
发送时间： 2019-10-28 16:12
收件人： ospanic/Captive_Portal_ESP
抄送： ospanic; Comment
主题： Re: [ospanic/Captive_Portal_ESP] 连接成功之后，并不会主动弹出那个界面？ (#1)
是需要添加一些 header 还是 meta 做些处理？

**Comment by xuhongv** [comment]
https://blog.csdn.net/bjbz_cxy/article/details/95231192 我看了看这个博客，貌似回调的内容要有所改变。你那时候也是用苹果手机测试过吗

**Comment by ospanic** [comment]
我在iphone6和iphonex上测试都能弹出页面的，部分安卓手机也可以的。示例中只是实现了dns重定向和http拦截，对于http返回的内容没有做太多的探索，每次访问返回的内容都是一样的。你可以试一下更改下网页内容或http响应头试下，如果有进展欢迎push到github


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 半颗心脏 | 徐宏 <notifications@github.com&gt;
发送时间: 2019年10月28日 17:13
收件人: ospanic/Captive_Portal_ESP <Captive_Portal_ESP@noreply.github.com&gt;
抄送: ospanic <ospanic@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ospanic/Captive_Portal_ESP] 连接成功之后，并不会主动弹出那个界面？ (#1)




https://blog.csdn.net/bjbz_cxy/article/details/95231192 我看了看这个博客，貌似回调的内容要有所改变。你那时候也是用苹果手机测试过吗

**Comment by xuhongv** [comment]
可以加个qq或者微信吗  我的微信是 870189248
